// Generated by staff_schema.py; do not edit.
#ifndef STAFF_WIRE_SCHEMA_MQH
#define STAFF_WIRE_SCHEMA_MQH
const int STAFF_WIRE_VALUE_COLUMNS = 50;
const uint STAFF_WIRE_SCHEMA_ID = 0x379D2170;
const string STAFF_EA_BUILD_HASH = "238f50f0b298f886648e07376a4bc7d40a78b8417b11386c19c9bf8354f25303";
const int STAFF_WIRE_FULL=1, STAFF_WIRE_ROW=2, STAFF_WIRE_HEARTBEAT=3;
const int STAFF_WIRE_HELLO=4, STAFF_WIRE_BUNDLE=5, STAFF_WIRE_ACK=6;
const int STAFF_COL_OPEN = 0; // open
const int STAFF_COL_HIGH = 1; // high
const int STAFF_COL_LOW = 2; // low
const int STAFF_COL_CLOSE = 3; // close
const int STAFF_COL_EMA_20 = 4; // ema_20
const int STAFF_COL_EMA_50 = 5; // ema_50
const int STAFF_COL_EMA_200 = 6; // ema_200
const int STAFF_COL_HMA_6 = 7; // hma_6
const int STAFF_COL_HMA_17 = 8; // hma_17
const int STAFF_COL_HMA_50 = 9; // hma_50
const int STAFF_COL_HMA_168 = 10; // hma_168
const int STAFF_COL_OPEN_BAND_4_MID = 11; // open_band_4_mid
const int STAFF_COL_PRICE_HMA_6 = 12; // price_hma_6
const int STAFF_COL_PRICE_BAND_LOWER = 13; // price_band_lower
const int STAFF_COL_PRICE_BAND_UPPER = 14; // price_band_upper
const int STAFF_COL_RSI_VAL = 15; // RSI_val
const int STAFF_COL_RSI_DB = 16; // RSI_db
const int STAFF_COL_RSI_UB = 17; // RSI_ub
const int STAFF_COL_RSI_BASIS = 18; // RSI_basis
const int STAFF_COL_STO_VAL = 19; // STO_val
const int STAFF_COL_STO_DB = 20; // STO_db
const int STAFF_COL_STO_UB = 21; // STO_ub
const int STAFF_COL_STO_BASIS = 22; // STO_basis
const int STAFF_COL_DI_VAL = 23; // DI_val
const int STAFF_COL_DI_DB = 24; // DI_db
const int STAFF_COL_DI_UB = 25; // DI_ub
const int STAFF_COL_DI_BASIS = 26; // DI_basis
const int STAFF_COL_PRICE_REGIME_BASIS = 27; // price_regime_basis
const int STAFF_COL_PRICE_REGIME_UPPER = 28; // price_regime_upper
const int STAFF_COL_PRICE_REGIME_LOWER = 29; // price_regime_lower
const int STAFF_COL_RSI_REGIME_UPPER = 30; // RSI_regime_upper
const int STAFF_COL_RSI_REGIME_LOWER = 31; // RSI_regime_lower
const int STAFF_COL_STO_REGIME_UPPER = 32; // STO_regime_upper
const int STAFF_COL_STO_REGIME_LOWER = 33; // STO_regime_lower
const int STAFF_COL_DI_REGIME_UPPER = 34; // DI_regime_upper
const int STAFF_COL_DI_REGIME_LOWER = 35; // DI_regime_lower
const int STAFF_COL_WONBI_UPPER = 36; // wonbi_upper
const int STAFF_COL_WONBI_LOWER = 37; // wonbi_lower
const int STAFF_COL_PRICE_LOWER_OUT = 38; // price_lower_out
const int STAFF_COL_PRICE_UPPER_OUT = 39; // price_upper_out
const int STAFF_COL_PRICE_REGIME_SLOPE = 40; // price_regime_slope
const int STAFF_COL_RSI_LOWER_OUT = 41; // RSI_lower_out
const int STAFF_COL_RSI_UPPER_OUT = 42; // RSI_upper_out
const int STAFF_COL_RSI_REGIME_SLOPE = 43; // RSI_regime_slope
const int STAFF_COL_STO_LOWER_OUT = 44; // STO_lower_out
const int STAFF_COL_STO_UPPER_OUT = 45; // STO_upper_out
const int STAFF_COL_STO_REGIME_SLOPE = 46; // STO_regime_slope
const int STAFF_COL_DI_LOWER_OUT = 47; // DI_lower_out
const int STAFF_COL_DI_UPPER_OUT = 48; // DI_upper_out
const int STAFF_COL_DI_REGIME_SLOPE = 49; // DI_regime_slope
#endif
